title: "Bar Chart"
status: wip
context:
  chart:
    - value: 127
      width: 100%
      label: Up to £500
    - value: 77
      width: 57%
      label: £501 - £1,000
    - value: 63
      width: 42%
      label: £1,001 - £2,000
    - value: 42
      width: 36%
      label: £2,001 - £5,000
    - value: 27
      width: 24%
      label: £5,001 - £10,000
    - value: 4
      width: 5%
      label: £10,001 - £100k