title: "Registry Card"
context:
  insights_card:
    publisher:
      name: A B Charitable Trust 
      website: http://abcharitabletrust.org.uk/
      logo: https://www.threesixtygiving.org/wp-content/uploads/Arcadia-Logo.jpg
    datasets:
      - title: Open Programme grants awarded from 2013 until April 2019,
        issued: '2018-06-21'
        url: http://abcharitabletrust.org.uk/awards.htm
        records: 593 
        amount: 8.5M
      - title: Open Programme grants awarded from 2013 until April 2019,
        issued: '2018-06-21'
        url: http://abcharitabletrust.org.uk/awards.htm
        records: 593 
        amount: 8.5M

