title: "Publication Years Chart"
notes: |
  Visualise distinctions in number of docs published – up to 10 – per period of time. Pass in the same number of elements for each data point which renders
  this component to keep the shading and widths comparable.
status: wip
context:
  chart:
    - label: Older Data
      value: 4
      detail: 4 published files before 2011
    - label: 2011
      value: 0
      detail: No published files in 2011
    - label: 2012
      value: 0
      detail: No published files in 2012
    - label: 2013
      value: 9
      detail: 9 published files in 2013
    - label: 2014
      value: 4
      detail: 4 published files in 2014
    - label: 2015
      value: 4
      detail: 4 published files in 2015
    - label: 2016
      value: 4
      detail: 4 published files in 2016
    - label: 2017
      value: 4
      detail: 4 published files in 2017
    - label: 2018
      value: 2
      detail: 2 published files in 2018
    - label: 2019
      value: 2
      detail: 2 published files in 2019
    - label: 2020
      value: 2
      detail: 2 published files in 2020
    - label: 2021
      value: 10
      detail: 10 published files in 2021
