title: Grant search result
status: ready
context:
  title: 'Grant to Help Musicians'
  url: '#'
  description: 'Toward the design of new educational and accessible materials, relating to the history of the Stoke Park Hospitals, which will increase the enjoyment and learning for a variety of audiences, but in particular those people with learning disabilities.'
  date: '22 Aug 2017'
  date_timestamp: '2017-08-22'
  amount: '£78,480'
  funder: 'Youth Music'
  funder_link: '#'
  recipient: 'Jack Drum Arts'
  recipient_link: '#'
  region: 'East Midlands'
  region_link: '#'
  district: 'Northampton District'
  district_link: '#'
