title: Filter type
status: ready
context:
  opened: true
  filterTypeLabel: 'Recipient region'
  filterItems:
    - label: 'Oxford (321)'
      url: '#'
      active: true
    - label: 'Reading (1422)'
      url: '#'
    - label: 'Manchester (3141)'
      url: '#'
      active: true
    - label: 'Birmingham (2132)'
      url: '#'
    - label: 'London (32113)'
      url: '#'
    - label: 'Paris (4123)'
      url: '#'
    - label: 'Marseille (7321)'
      url: '#'
    - label: 'Brussels (9321)'
      url: '#'
    - label: 'Geneva (8743)'
      url: '#'
    - label: 'Barcelona (8241)'
      url: '#'
