context:
  header:
    th1: Title
    th2: Description
    th3: Type
    th4: Required
  body:
    - row:
        cell1: Identifier
        cell2: The unique identifier for this grant. Made up of your 360Giving prefix, and an identifier from your records. See the 360Giving Grant identifier guidance for details.
        cell3: string
        cell4: True
    - row:
        cell1: Title
        cell2: A title for this grant activity. This should be under 140 characters long.
        cell3: string
        cell4: True
    - row:
        cell1: Description
        cell2: A short description of this grant activity. 
        cell3: string
        cell4: True
    - row:
        cell1: Currency
        cell2: "The currency used in amounts. Use the three-letter <a href='#'>currency code from ISO 4217</a> eg: Use GBP for Pounds Sterling."
        cell3: string
        cell4: True
    - row:
        cell1: Amount Applied For  
        cell2: Total amount applied for in numbers (do not include commas or currency symbols such as £). If you have provided detailed transaction information on a separate table, this should equal the sum of all the application transactions for this grant. 
        cell3: number
        cell4: False
    - row:
        cell1: Amount Awarded  
        cell2: Total amount awarded in numbers (do not include commas or currency symbols such as £). If you have provided detailed transaction information on a separate table, this should equal the sum of all the award transactions for this grant. 
        cell3: number
        cell4: True
    - row:
        cell1: Amount Disbursed  
        cell2: "Total amount disbursed (paid) to this grantee when this record was last updated (in numbers: do not include commas or currency symbols such as £)). If you have provided detailed transaction information on a separate table, this should equal the sum of all the disbursement transactions for this grant." 
        cell3: number
        cell4: False
    - row:
        cell1: Award Date  
        cell2: When was the decision to award this grant made. The date should be written as YYYY-MM-DD, or in full date-time format.  
        cell3: string
        cell4: True
variants:
  - name: Publishers
    context:
      sections:
        - heading: Location
          items:
            - icon:
                icon_name: add_location
              label: Include recipient locations
              value: 64%
            - icon:
                icon_name: add_location
              label: Include grant location names
              value: 63%
            - icon:
                icon_name: add_location
              label: Include grant location codes
              value: 62%
        - heading: Organisation Information
          items:
            - icon:
                icon_name: tag
              label: Include charity or company no
              value: 64%
            - icon:
                icon_name: confirmation_number
              label: Include external identifiers
              value: 45%
        - heading: Grant Information
          items:
            - icon:
                icon_name: timer
              label: Include grant duration
              value: 57%
            - icon:
                icon_name: format_quote
              label: Include grant programme names
              value: 56%
            - icon:
                icon_name: category
              label: Include grant classifications
              value: 55%
        - heading: Files
          items:
            - icon:
                icon_name: table_rows
              label: Include metadata
              value: 81%
            - icon:
                overlaid_text: json
              label: Publish using JSON
              value: 75%
            - icon:
                overlaid_text: xlsx
              label: Publish using spreadsheets
              value: 79%
        - heading: Up To Date
          items:
            - icon:
                icon_name: event_available
              label: Published data in the last year
              value: 91%
            - icon:
                icon_name: event_available
              label: Published data in the last month 
              value: 88%
