label: Sort &amp; Filter Bar
status: ready
context:
  filters:
    - label: Alphabetically
      active: true
      status: Sorting alphabetically
    - label: Filter by publisher
      active: false
