label: Sort &amp; Filter Bar
status: ready
context:
  filters:
    - label: Alphabetically
      active: true
      status: Sorting alphabetically
    - label: Filter by recipient
      active: false
    - label: Filter by data feature
      active: true
      selected_item: Include charity or company nos.
      status: 'Filtering by: Include charity or company nos.'
    - label: Filter by data file
      active: false
    - label: Filter by data file
      active: false
