title: "Registry Card"
context:
  title: Open Programme grants awarded from 2013 until April 2019
  data:
    title: Open Programme grants awarded from 2013 until April 2019,
    description: 
    identifier: a001p00000zgyHZAAY"
    license: https://creativecommons.org/licenses/by/4.0/
    license_name: Creative Commons Attribution 4.0 International (CC BY 4.0)
    issued: 2018-06-21,
    modified: 2019-07-19T13:16:14.000+0000,
    publisher:
      name: A B Charitable Trust 
      website: http://abcharitabletrust.org.uk/
      logo: https://www.threesixtygiving.org/wp-content/uploads/Arcadia-Logo.jpg
      prefix: 360G-ABCT
    distribution:
      downloadURL: http://abcharitabletrust.org.uk/data/abct-data.xlsx,
      accessURL: http://abcharitabletrust.org.uk/awards.htm,
      title: Open Programme grants awarded from 2013 until April 2019
