title: "Colours"
status: ready
context:
  main_colors:
    - name: Base
      values:
        hex: "#153634"
        rgba: "21, 54, 52"
        hsl: "243, 75%,  6%"
      vars:
        css_hsl: --base-hsl
        css_hsla: --color-base
        sass: "$base"
      alias: 
        - "--color-default"
      shades:
        - "#050E0D"
        - "#0B1B1A"
        - "#102927"
      tints:
        - "#506867"
        - "#8A9B99"
        - "#C5CDCC"

    - name: Orange
      values:
        hex: "#DE6E26"
        rgba: "222, 110, 38"
        hsl: "23, 74%, 51%"        
      vars:
        css_hsl: --orange-hsl
        css_hsla: --color-orange
        sass: "$orange"
      alias: 
        - "--color-primary"
      shades:
        - "#381C0A"
        - "#6F3713"
        - "#A7531D"
      tints:
        - "#E6925C"
        - "#EFB793"
        - "#F7DBC9"
      text:
        values:
          hex: "#A7531D"
          rgba: "166, 84, 29"
          hsl: "24, 70%, 38%"  
        vars:
          css_hsl: --orange-dark-hsl
          css_hsla: --color-orange-dark
          sass: "$orange-dark"

    - name: Teal
      values:
        hex: "#4DACB6"
        rgba: "77, 172, 182"
        hsl: "186, 42%, 51%"  
      vars:
        css_hsl: --teal-hsl
        css_hsla: --color-teal
        sass: "$teal"
      alias: 
        - "--color-accent"
      shades:
        - "#132B2D"
        - "#27565B"
        - "#3a8088"
      tints:
        - "#7AC1C8"
        - "#A6D6DA"
        - "#D3EAED"
      text:
        values:
          hex: "#2e666b"
          rgba: "46, 102, 107"
          hsl: "185, 40%, 30%"  
        vars:
          css_hsl: --teal-dark-hsl
          css_hsla: --color-teal-dark
          sass: "$teal-dark"

    - name: Yellow
      values:
        hex: "#EFC329"
        rgba: "239, 195, 41"
        hsl: "47, 86%, 55%"
      vars:
        css_hsl: --yellow-hsl
        css_hsla: --color-yellow
        sass: "$yellow"
      shades:
        - "#3C310A"
        - "#8e7419"
        - "#B3921F"
      tints:
        - "#F3D25E"
        - "#F7E194"
        - "#FBF0C9"
      text:
        values:
          hex: "#8f730c"
          rgba: "143, 116, 12"
          hsl: "47, 85%, 30%"  
        vars:
          css_hsl: --yellow-dark-hsl
          css_hsla: --color-yellow-dark
          sass: "$yellow-dark"

    - name: Red
      values:
        hex: "#BC2C26"
        rgba: "188, 44, 38"
        hsl: "2, 66%, 44%"
      vars:
        css_hsl: --red-hsl
        css_hsla: --color-red
        sass: "$red"
      shades:
        - "#2F0B0A"
        - "#5E1613"
        - "#8D211D"
      tints:
        - "#CD615C"
        - "#DE9593"
        - "#EECAC9"

  secondary_colors:
    - name: Success Green
      values:
        hex: "#00571d"
        rgba: "0, 87, 29, 1"
        hsl: "140, 100%, 17%"
      vars:
        css_hsl: --success-green-hsl
        css_hsla: --color-success
        sass: "$success"

    - name: Error Red
      values:
        hex: "#BC2C26"
        rgba: "188, 44, 38"
        hsl: "2, 66%, 44%"
      vars:
        css_hsl: --error-red-hsl
        css_hsla: --color-error
        sass: "$error"

    - name: Warning Yellow
      values:
        hex: "#EFC329"
        rgba: "239, 195, 41"
        hsl: "47, 86%, 55%"
      vars:
        css_hsl: --warning-yellow-hsl
        css_hsla: --color-warning
        sass: "$warning"
