title: 'Page title'
status: ready
context:
  title: 'Chloroquine/Hydroxychloroquine prevention of coronavirus disease (COVID-19) in the healthcare setting; a randomised, placebo-controlled prophylaxis study (COPCOV)'
  id: '(360G-SE-2010008706LOTT_2010-11-10)'
  id_url: '#'
