title: "Search block"
status: ready
context:
  description: 'Search, explore and download UK grants data published by funders in the 360Giving Data Standard.'
  form_action: '#'
  submit_text: 'Search'
