title: 'Pager'
status: ready
context:
  pages:
    - label: 'First'
      type: 'first'
      url: '#'
    - label: 'Previous'
      type: 'prev'
      url: '#'
    - type: 'ellipsis'
    - label: '3'
      type: 'number'
      url: '#'
    - label: '4'
      type: 'number'
      url: '#'
    - label: '5'
      type: 'number'
      url: '#'
    - label: '6'
      type: 'number'
      url: '#'
    - label: '7'
      type: 'number'
      url: '#'
    - label: '8'
      type: 'number'
      url: '#'
    - type: 'ellipsis'
    - label: 'Next'
      type: 'next'
      url: '#'
    - label: 'Last'
      type: 'last'
      url: '#'
variants:
  - name: First page
    context:
      pages:
        - label: 'First'
          type: 'first'
          url: '#'
        - label: 'Previous'
          type: 'prev'
          url: '#'
        - label: '1'
          type: 'number'
          url: '#'
        - label: '2'
          type: 'number'
          url: '#'
        - label: '3'
          type: 'number'
          url: '#'
        - label: '4'
          type: 'number'
          url: '#'
        - label: '5'
          type: 'number'
          url: '#'
        - label: '6'
          type: 'number'
          url: '#'
        - type: 'ellipsis'
        - label: 'Next'
          type: 'next'
          url: '#'
        - label: 'Last'
          type: 'last'
          url: '#'
  - name: simple
    context:
      pages:
        - label: 'Previous'
          type: 'prev'
          url: '#'
        - label: 'Next'
          type: 'next'
          url: '#'
