status: ready
collated: true
variants:
  - name: default
    label: Material Icon
    context:
      icon_name: 'add_location'
      label: 'Includes recipient locations'
  - name: black
    label: Material Icon In Black
    context:
      icon_name: 'add_location'
      label: 'Includes recipient locations'
  - name: orange
    label: Material Icon In Orange
    context:
      icon_name: 'add_location'
      label: 'Includes recipient locations'
  - name: Overlaid Text
    context:
      overlaid_text: CSV
      label: CSV files
